# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Fantastic_Group_Project
                                 A QGIS plugin
 Election prediction plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-03-20
        copyright            : (C) 2019 by Fantastic Four .group
        email                : notYet@bruh.mp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Fantastic_Group_Project class from file Fantastic_Group_Project.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .election_plugin import Fantastic_Group_Project
    return Fantastic_Group_Project(iface)
